<regex> ::= "!"? <term> (("|" | "&") <regex>)?
<term> ::= <factor>*
<factor> ::= <atom> ("*" | "+" | "?")?
<atom> ::= "%" | "(" <regex> ")" | "~"? ("." | <symbol> ("-" <symbol>)?)
<symbol> ::= "\\" <metachar> | (? any character except <metachar> ?)
<metachar> ::= (? one of "\-.~%*+?|&!()" ?)
